### ISSUE TITLE
[feature request] Rounded corners

### ISSUE THREAD

**Issue by ReidE96** [gameclosure/devkit#113]
With CSS3 this is increasingly a viable thing, since there's no longer a need to mess around with divs and small corner image things. So our artist has made all sorts of things with rounded corners. Is there some way `View`s just using `backgroundColor` could have rounded corners for display? (obviously still be square in location, just visibly rounded corners)

**Comment by jwilm** [comment]
We've got a branch of [`timestep`](https://github.com/gameclosure/timestep/pull/43) with a class named `MaskedImageView`. It's undocumented, but it would achieve what you're looking for without too much overhead (or effort on your part). We _could_ potentially add a parameter for image views which generates a mask automatically and uses MaskedImageView under the hood. Closing this with _wont fix_ since there is a fairly trivial solution in the mean time.
